### ISSUE TITLE
Fifo full vs overflow behaviour

### ISSUE THREAD

**Issue by adumont** [ZipCPU/wbuart32#3]
I'm using your ufifo.v module in my HRMCPU project and I noticed something I don't understand.

Is it correct to assume that o_err means that the fifo is full (and hence shouldn't be written to until some slot is freed up with a read?

I was using o_err signal as a fifo_is_full flag, but I noticed that once the fifo is full (o_err get value 1), even if you read values from the fifo, o_err (or r_ovfl) never gets 0 again, unless reset is asserted. is that normal?

I suspect I might be using the wrong signal (o_err) to know if the fifo is full or not... Am I?

**Comment by ZipCPU** [comment]
Yes, you are using the wrong signal to know if the FIFO is full or now.  The err signal is set if you actually overflow the FIFO, and then cleared when you reset the FIFO to acknowledge the error--just as you noticed.

To know if the FIFO is actually full, you need to check the bottom bit of the status register, o_status.  On a receive FIFO, where RXFIFO == 1'b1, this will be true if anything is within the FIFO that may then be read.  For a transmit FIFO, where RXFIFO == 1'b0, this will be true if the FIFO is not full and so something may be written to the FIFO.

Alternatively, bits [11:2] contain the number of items in the FIFO.  You can use those as well to check if the FIFO is full.  In other words, when `((status & 0xffc) == 0xffc)` you also know that the FIFO is full.

**Comment by adumont** [comment]
Thanks Dan, I'll review your comment and keep that in mind in my design.
