### ISSUE TITLE
Help needed in the standalone testbench part 

### ISSUE THREAD

**Issue by akashjcp22** [ZipCPU/wbuart32#7]
Hi
I am trying to simulate the receiver part. In using your echo test as a standalone test how do I input values to the receiver?. Here you have shown the testing logic but how to give proper data and test. In the HelloWorld test, transmitting was very clear by turning ON/OFF suitable registers and by exactly putting data in tx_data. In the receiver testing side how to do that, please help. Thanks in advance.

**Comment by ZipCPU** [comment]
Have you looked at how this is done within the [linetest](https://github.com/ZipCPU/wbuart32/blob/master/rtl/linetest.v)?  The line test accepts a line of data and then outputs it once the line is complete.

Either way, the input to [the receiver](https://github.com/ZipCPU/wbuart32/blob/master/rtl/rxuart.v) is a single bit coming from the serial port.  In the echo test, this bit needs to be generated externally.  In the [emulator](https://github.com/ZipCPU/wbuart32/blob/master/bench/cpp/uartsim.cpp) the bit that needs to be received by the design is the output of the [operator() function](https://github.com/ZipCPU/wbuart32/blob/master/bench/cpp/uartsim.h#L123-L124).  This function takes its inputs either from STDIN or from [a TCP/IP network port](https://zipcpu.com/blog/2017/06/17/why-network-debugging.html) depending upon how you set it up.

To see how this might work, feel free to check out [this ZipCPU example](https://zipcpu.com/zipcpu/2018/02/12/zbasic-intro.html), which allows you to play 4x4x4 Tic-Tac-Toe with the ZipCPU running within Verilator.

As for the STDIN approach, I discuss it in detail in [my tutorial](https://zipcpu.com/tutorial) where we rebuild the serial port simulator from the ground up and as well as a line test project to go with it.

Beyond that, it might help to be clearer about what you are looking for.

Dan
